### ISSUE TITLE
resize partition sd card

### ISSUE THREAD

**Issue by frddbbbl** [khumarahn/teres1-gentoo#3]
Hi, I have been trying to resize the root partition from the image however no software seems able to do so, I have tried GParted, parted, and disk utility and all of them run into errors when trying to read the root partion, is this to do with the image or could it possibly be to do with the sd card?

**Comment by khumarahn** [comment]
Hi. This is more involved that I'd like it to be. The reason is f2fs. It works nice on Teres, visibly faster than ext4 or anything else. But f2fs is recent and has been changing in the past 10 years. So much so that newer linux kernels cannot understand f2fs of the Teres' ancient 3.10 kernel. This means, you can't resize it on any up-to-date computer. In fact, I would not recommend even mounting the root partition on an up-to-date computer.

What should work: boot from Teres stock Ubuntu, with the 3.10 kernel. Insert the sd card with gentoo. Then:
* resize the partition:
  * `fdisk /dev/mmcblk1`
  * delete second partition and create a new one starting with the same block
* resize the filesystem: `resize.f2fs /dev/mmcblk1p1`.

It is always possible to replace f2fs with ext4 or similar.

P.S.: Following sunxi and armbian, I am running very recent kernels now with Gentoo, and old-f2fs problems are gone. But here suspend, sound, LEDs etc do not work well yet. So it is hard to say what is better.

**Comment by frddbbbl** [comment]
Hi. I successfully resized the partition how ever olimex's ubuntu does not seem to recognise resize.f2fs as a command inspire of f2fs-tools being installed

**Comment by khumarahn** [comment]
ok. resize.f2fs appeared later, f2fs-tools from Ubuntu 18.04 would have it.

Try this, as root under ubuntu, if `/dev/mmcblk1` is the sd card with gentoo:
* mount gentoo's root filesystem somewhere `mount /dev/mmvblk1p2 /mnt`
* save the contents (the slash after `/mnt` is important): 
```
mkdir /gentoo-root
rsync -aAxXhH -v /mnt/ /gentoo-root/
```
* create a new filesystem on gentoo partition f2fs or other:
```
umount /mnt
mkfs.f2fs -f /dev/mmcblk1p2
```
* mount and restore the data (again, the slash after `/gentoo-root` is important):
```
mount /dev/mmcblk1p2 /mnt
rsync -aAxXhH -v /gentoo-root/ /mnt
```

**Comment by frddbbbl** [comment]
Hi Ive got to creating the new file system but I don't think -f is an option for mkfs.f2fs?

**Comment by khumarahn** [comment]
It is for overwrite of the previous filesystem. It is OK if you don't need it.
http://manpages.ubuntu.com/manpages/bionic/man8/mkfs.f2fs.8.html

**Comment by frddbbbl** [comment]
thanks, the newer version of f2fs-tools installed just overwrote it automatically I have now re-sized the partition!
